name:                katas-codewars
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- hspec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  katas-codewars-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - katas-codewars
    ghc-options:
    - -fwarn-tabs


tests:
  katas-codewars-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - katas-codewars
    ghc-options:
    - -fwarn-tabs
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
